# Generated by Django 2.0.3 on 2018-03-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.URLField(blank=True),
        ),
    ]
